project:
  type: website

website:
  #title: "CAPB_web"
  back-to-top-navigation: true
  navbar:
    collapse-below: xl
    logo: "images/logos/Panorama2.png"
    logo-alt: "ZAE Marticot"
    left:
      - href: index.qmd
        icon: house
        text: Accueil
      # - href: methodologie.qmd
      #   text: Méthodologie
      #   icon: flask
      - href: cartes.qmd
        icon: map
        text: Cartes
      - text: Méthodologie/Exploitation questionnaire
        icon: pen
        menu:
          - href: methodologie.qmd
            text: Méthodologie
          - href: etat_civil.qmd
            text: Volet Etat civil
          - text: Volet Perception générale
            href: perception_generale.qmd
          - text: Volet vie professionnelle
            href: vie_professionnelle.qmd
          - text: Volet Perception de l'environnement et des conditions de travail
            href: percpetion_environnement.qmd
          - text: Volet Modalités de transports
            href: modalites_transports.qmd
          - text: Volet Pause déjeuner
            href: pause_dejeuner.qmd
          - text: Conclusion
            href: conclusion.qmd
      #- href: ref_biblio.qmd
        #text: Références biliographiques
        #icon: book
  page-footer:
    left: "Site créé avec [Quarto](https://quarto.org/)"
    center: "©CEREMA"
    right: 
      - icon: linkedin
        href: https://fr.linkedin.com/company/cerema
      - icon: twitter-x 
        href: https://x.com/ceremacom
      - icon: youtube
        href: https://www.youtube.com/@cerema3139 

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    toc-title: Contenu
    toc-location: left
    toc-depth: 2
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    

editor: visual


